# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmNkZDNhNzU3MGViNzZiMWJhOGYxMGMyMDMyOTcyMzZjYzlmZGU5ZDllY2E1YWFmZGYzNTBmNWY1MDExMWQzZDZkMDMzOTc3NDU2MmMwYzk2ZDM2N2NjZTJlNGVlMGNkZWQ2MzRlYzRiYzVlMjdlOWMzNTlmY2M5ZDBiODExN2E=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
